#include<stdio.h>
int main()
{
  long int a[100001],b[100001]={0},t,n,i,np,f=0;
   scanf("%ld",&t);
   while(t--)
   {
   	   np=1;
       scanf("%ld",&n);
       for(i=1;i<=n;i++)
       {
           scanf("%ld",&a[i]);
       }
       i=1;
        while(i<=n)
        {
            np=a[np];
            i++;
            if(np==n)
            {
                f=1;
                printf("YES\n");
                break;
            }
            if(b[np]==0)
            {
            b[np]++;
            }
            else
            {
                f=1;
                printf("NO\n");
                break;
            }
        }
        if(f==0)
        {
             printf("NO\n");
        }
   }
   return 0;
}
