#include<stdio.h>
#include<string.h>
char a[10000000];
int main()
{
   long long int d,i,l,f,m,c,j;
   scanf("%lld",&d);
   while(d--)
   {
    scanf("%s",a);
    l=strlen(a);
    if(l==1)
    {
        printf("NO\n");
    }
    else if(l==3)
    {
        if(a[0]==a[1] || a[1]==a[2] || a[2]==a[0])
        {
            printf("YES\n");
        }
        else
        {
            printf("NO\n");
        }
    }
    else
    {
        f=0;
        m=l/2;
        if(l%2==0)
        {
            f=0;
            for(i=0;i<m;i++)
            {
                if(a[i]!=a[i+m])
                {
                    f=1;
                    break;
                }
            }
            if(f==0)
            {
                printf("YES\n");
            }
            else
            {
                printf("NO\n");
            }
        }
        else
        {
            f=0;
            j=m;
            c=0;
            for(i=0;i<m;i++)
            {
                if(a[i]!=a[j])
                {
                    if(c==0)
                    {
                        i--;
                        c=1;
                    }
                    else
                    {
                        f=1;
                        break;
                    }
                }
                j++;
            }
            if(f==1)
            {
              j=m+1;
              c=0;
              f=0;
              for(i=0;i<m+1;i++)
              {
                if(a[i]!=a[j])
                {
                    if(c==0)
                    {
                        j--;
                        c=1;
                    }
                    else
                    {
                        f=1;
                        break;
                    }
                }
                j++;
              }
            }
             if(f==0)
            {
                printf("YES\n");
            }
            else
            {
                printf("NO\n");
            }

       }

    }
   }
    return 0;
}
