#include<stdio.h>
int main()
{
   int n,i,j,k,c=1,a[101][101],nr,nc,x,y,p=0;
   int v[1000][2],vt=0;
   scanf("%d",&n);
   i=0;
   j=0;
   nr=nc=n;
   p=1;
   while(i<nr&&j<nc)
   {
         for(k=j;k<nc;k++)
        {
            a[i][k]=c;
            c++;
           // cout<<a[i][k]<<"hm h"<<endl;
        }
        i++;
         for(k=i;k<nr;k++)
        {
            a[k][nc-1]=c;
            c++;
        }
        nc--;
        if(i<nr)
        {
            for(k=nc-1;k>=j;k--)
            {
                a[nr-1][k]=c;
                c++;
            }
            nr--;
        }
        if(j<nc)
        {
            for(k=nr-1;k>=i;k--)
            {
                a[k][j]=c;
                c++;
            }
            j++;
        }
   }
    for(i=0;i<n;i++)
    {
        for(j=0;j<n;j++)
        {
            printf("%d ",a[i][j]);
        }
        printf("\n");
    }
    i=0;j=0;
    k=0;
    nc=nr=n;
    v[vt][0]=0;
    v[vt][1]=0;
    vt++;
    while(i<nr&&j<nc)
   {
         for(k=j;k<nc;k++)
        {
            if(a[i][k]%11==0)
            {
                p++;
                v[vt][0]=i;
                v[vt][1]=k;
                vt++;
            }
        }
        i++;
         for(k=i;k<nr;k++)
        {
            if(a[k][nc-1]%11==0)
            {
                p++;
                v[vt][0]=k;
                v[vt][1]=nc-1;
                vt++;
            }
        }
        nc--;
        if(i<nr)
        {
            for(k=nc-1;k>=j;k--)
            {
               if(a[nr-1][k]%11==0)
            {
                p++;
                v[vt][0]=nr-1;
                v[vt][1]=k;
                vt++;
            }
            }
            nr--;
        }
        if(j<nc)
        {
            for(k=nr-1;k>=i;k--)
            {
                a[k][j]=c;
                if(a[k][j]%11==0)
            {
                p++;
                v[vt][0]=k;
                v[vt][1]=j;
                vt++;
            }
            }
            j++;
        }
   }
   printf("Total Power points : %d\n",p);
    for(i=0;i<vt;i++)
    {
        printf("(%d,%d)\n",v[i][0],v[i][1]);
    }
}


